# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1175, 751)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1175, 751))
        MainWindow.setMaximumSize(QtCore.QSize(1175, 751))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_2013 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2013.setGeometry(QtCore.QRect(110, 50, 81, 21))
        self.btn_2013.setWhatsThis("")
        self.btn_2013.setAutoFillBackground(False)
        self.btn_2013.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.btn_2013.setAutoDefault(False)
        self.btn_2013.setObjectName("btn_2013")
        self.All_bez_back = QtWidgets.QPushButton(self.centralwidget)
        self.All_bez_back.setGeometry(QtCore.QRect(10, 50, 91, 23))
        self.All_bez_back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(107, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.All_bez_back.setObjectName("All_bez_back")
        self.AIS_btn = QtWidgets.QPushButton(self.centralwidget)
        self.AIS_btn.setGeometry(QtCore.QRect(270, 260, 81, 31))
        self.AIS_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(112, 48,160,255) stop:0.935 rgba(223, 201, 239, 255));")
        self.AIS_btn.setObjectName("AIS_btn")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 670, 1151, 31))
        self.progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.Sroki_Svod_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Sroki_Svod_btn.setGeometry(QtCore.QRect(10, 80, 91, 23))
        self.Sroki_Svod_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(107, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.Sroki_Svod_btn.setObjectName("Sroki_Svod_btn")
        self.Matrica_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Matrica_btn.setGeometry(QtCore.QRect(10, 110, 91, 23))
        self.Matrica_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(197, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.Matrica_btn.setObjectName("Matrica_btn")
        self.Prosrozka_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Prosrozka_btn.setGeometry(QtCore.QRect(10, 140, 91, 23))
        self.Prosrozka_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(197, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.Prosrozka_btn.setObjectName("Prosrozka_btn")
        self.BLACK_Q_btn = QtWidgets.QPushButton(self.centralwidget)
        self.BLACK_Q_btn.setGeometry(QtCore.QRect(10, 170, 91, 23))
        self.BLACK_Q_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(107, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.BLACK_Q_btn.setObjectName("BLACK_Q_btn")
        self.SPY_MIN_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SPY_MIN_btn.setGeometry(QtCore.QRect(10, 200, 91, 23))
        self.SPY_MIN_btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(197, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.SPY_MIN_btn.setObjectName("SPY_MIN_btn")
        self.prosrozka_exc = QtWidgets.QPushButton(self.centralwidget)
        self.prosrozka_exc.setGeometry(QtCore.QRect(110, 140, 81, 23))
        self.prosrozka_exc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prosrozka_exc.setAccessibleDescription("")
        self.prosrozka_exc.setAutoFillBackground(False)
        self.prosrozka_exc.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        icon = QtGui.QIcon.fromTheme("Excel")
        self.prosrozka_exc.setIcon(icon)
        self.prosrozka_exc.setObjectName("prosrozka_exc")
        self.black_q_exc = QtWidgets.QPushButton(self.centralwidget)
        self.black_q_exc.setGeometry(QtCore.QRect(110, 170, 81, 23))
        self.black_q_exc.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.black_q_exc.setObjectName("black_q_exc")
        self.spy_min_exc = QtWidgets.QPushButton(self.centralwidget)
        self.spy_min_exc.setGeometry(QtCore.QRect(110, 200, 81, 23))
        self.spy_min_exc.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.spy_min_exc.setObjectName("spy_min_exc")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 290, 860, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_106 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_106.setGeometry(QtCore.QRect(270, 80, 81, 31))
        self.btn_106.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(112, 48,160,255) stop:0.935 rgba(223, 201, 239, 255));")
        self.btn_106.setObjectName("btn_106")
        self.LinkBox = QtWidgets.QComboBox(self.centralwidget)
        self.LinkBox.setGeometry(QtCore.QRect(930, 0, 151, 22))
        self.LinkBox.setObjectName("LinkBox")
        self.LinkBox.addItem("")
        self.LinkBox.addItem("")
        self.LinkBox.addItem("")
        self.LinkBox.addItem("")
        self.LinkBox.addItem("")
        self.LinkBox.addItem("")
        self.LinkBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(880, 0, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.calendar107 = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar107.setGeometry(QtCore.QRect(860, 30, 311, 201))
        self.calendar107.setGridVisible(False)
        self.calendar107.setDateEditEnabled(True)
        self.calendar107.setObjectName("calendar107")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 70, 501, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 25, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.reservButton = QtWidgets.QPushButton(self.centralwidget)
        self.reservButton.setGeometry(QtCore.QRect(20, 610, 111, 51))
        self.reservButton.setObjectName("reservButton")
        self.FileAisInfo = QtWidgets.QLCDNumber(self.centralwidget)
        self.FileAisInfo.setGeometry(QtCore.QRect(370, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.FileAisInfo.setFont(font)
        self.FileAisInfo.setSmallDecimalPoint(False)
        self.FileAisInfo.setDigitCount(6)
        self.FileAisInfo.setMode(QtWidgets.QLCDNumber.Dec)
        self.FileAisInfo.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.FileAisInfo.setProperty("value", 53871.0)
        self.FileAisInfo.setObjectName("FileAisInfo")
        self.labelAisText = QtWidgets.QLabel(self.centralwidget)
        self.labelAisText.setGeometry(QtCore.QRect(490, 240, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.labelAisText.setFont(font)
        self.labelAisText.setObjectName("labelAisText")
        self.FileAisInfo_base = QtWidgets.QLCDNumber(self.centralwidget)
        self.FileAisInfo_base.setGeometry(QtCore.QRect(490, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.FileAisInfo_base.setFont(font)
        self.FileAisInfo_base.setSmallDecimalPoint(False)
        self.FileAisInfo_base.setDigitCount(6)
        self.FileAisInfo_base.setMode(QtWidgets.QLCDNumber.Dec)
        self.FileAisInfo_base.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.FileAisInfo_base.setProperty("value", 53871.0)
        self.FileAisInfo_base.setObjectName("FileAisInfo_base")
        self.labelAisText_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelAisText_2.setGeometry(QtCore.QRect(370, 240, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.labelAisText_2.setFont(font)
        self.labelAisText_2.setObjectName("labelAisText_2")
        self.reserv_adress = QtWidgets.QLabel(self.centralwidget)
        self.reserv_adress.setGeometry(QtCore.QRect(20, 580, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.reserv_adress.setFont(font)
        self.reserv_adress.setObjectName("reserv_adress")
        self.tableWidget101 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget101.setGeometry(QtCore.QRect(270, 110, 581, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget101.sizePolicy().hasHeightForWidth())
        self.tableWidget101.setSizePolicy(sizePolicy)
        self.tableWidget101.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget101.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget101.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidget101.setLineWidth(1)
        self.tableWidget101.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget101.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget101.setTabKeyNavigation(False)
        self.tableWidget101.setDragDropOverwriteMode(False)
        self.tableWidget101.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget101.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget101.setColumnCount(2)
        self.tableWidget101.setObjectName("tableWidget101")
        self.tableWidget101.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget101.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget101.setHorizontalHeaderItem(1, item)
        self.tableWidget101.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget101.horizontalHeader().setDefaultSectionSize(290)
        self.tableWidget101.horizontalHeader().setMinimumSectionSize(10)
        self.checkBox106 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox106.setGeometry(QtCore.QRect(370, 86, 161, 21))
        self.checkBox106.setChecked(True)
        self.checkBox106.setObjectName("checkBox106")
        self.info106labelTime = QtWidgets.QLabel(self.centralwidget)
        self.info106labelTime.setGeometry(QtCore.QRect(540, 79, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.info106labelTime.setFont(font)
        self.info106labelTime.setObjectName("info106labelTime")
        self.date106Info = QtWidgets.QLabel(self.centralwidget)
        self.date106Info.setGeometry(QtCore.QRect(680, 79, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date106Info.setFont(font)
        self.date106Info.setObjectName("date106Info")
        self.vsesrazu = QtWidgets.QPushButton(self.centralwidget)
        self.vsesrazu.setGeometry(QtCore.QRect(10, 302, 91, 31))
        self.vsesrazu.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(197, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.vsesrazu.setObjectName("vsesrazu")
        self.send_daily_stat = QtWidgets.QPushButton(self.centralwidget)
        self.send_daily_stat.setGeometry(QtCore.QRect(110, 300, 111, 31))
        self.send_daily_stat.setObjectName("send_daily_stat")
        self.changedinfo = QtWidgets.QTableWidget(self.centralwidget)
        self.changedinfo.setGeometry(QtCore.QRect(140, 580, 271, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changedinfo.sizePolicy().hasHeightForWidth())
        self.changedinfo.setSizePolicy(sizePolicy)
        self.changedinfo.setMinimumSize(QtCore.QSize(0, 0))
        self.changedinfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.changedinfo.setFrameShape(QtWidgets.QFrame.Panel)
        self.changedinfo.setLineWidth(1)
        self.changedinfo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.changedinfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.changedinfo.setTabKeyNavigation(False)
        self.changedinfo.setDragDropOverwriteMode(False)
        self.changedinfo.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.changedinfo.setGridStyle(QtCore.Qt.SolidLine)
        self.changedinfo.setColumnCount(2)
        self.changedinfo.setObjectName("changedinfo")
        self.changedinfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.changedinfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.changedinfo.setHorizontalHeaderItem(1, item)
        self.changedinfo.horizontalHeader().setCascadingSectionResizes(False)
        self.changedinfo.horizontalHeader().setDefaultSectionSize(137)
        self.changedinfo.horizontalHeader().setMinimumSectionSize(10)
        self.labelchanged = QtWidgets.QLabel(self.centralwidget)
        self.labelchanged.setGeometry(QtCore.QRect(140, 550, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelchanged.setFont(font)
        self.labelchanged.setObjectName("labelchanged")
        self.BIG_ZAP = QtWidgets.QPushButton(self.centralwidget)
        self.BIG_ZAP.setGeometry(QtCore.QRect(10, 380, 91, 31))
        self.BIG_ZAP.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(197, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.BIG_ZAP.setObjectName("BIG_ZAP")
        self.toloko = QtWidgets.QPushButton(self.centralwidget)
        self.toloko.setGeometry(QtCore.QRect(310, 340, 71, 31))
        self.toloko.setObjectName("toloko")
        self.blue_submit = QtWidgets.QLabel(self.centralwidget)
        self.blue_submit.setGeometry(QtCore.QRect(390, 350, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.blue_submit.setFont(font)
        self.blue_submit.setObjectName("blue_submit")
        self.priloj_4 = QtWidgets.QPushButton(self.centralwidget)
        self.priloj_4.setGeometry(QtCore.QRect(110, 380, 81, 31))
        self.priloj_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.priloj_4.setAccessibleDescription("")
        self.priloj_4.setAutoFillBackground(False)
        self.priloj_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        icon = QtGui.QIcon.fromTheme("Excel")
        self.priloj_4.setIcon(icon)
        self.priloj_4.setObjectName("priloj_4")
        self.BIG_SREZ = QtWidgets.QPushButton(self.centralwidget)
        self.BIG_SREZ.setGeometry(QtCore.QRect(200, 340, 101, 31))
        self.BIG_SREZ.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(197, 90,17,255) stop:0.935 rgba(247, 197, 163, 255));")
        self.BIG_SREZ.setObjectName("BIG_SREZ")
        self.andreeva = QtWidgets.QPushButton(self.centralwidget)
        self.andreeva.setGeometry(QtCore.QRect(310, 380, 71, 31))
        self.andreeva.setObjectName("andreeva")
        self.priloj_4_srez = QtWidgets.QPushButton(self.centralwidget)
        self.priloj_4_srez.setGeometry(QtCore.QRect(200, 380, 101, 31))
        self.priloj_4_srez.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.priloj_4_srez.setAccessibleDescription("")
        self.priloj_4_srez.setAutoFillBackground(False)
        self.priloj_4_srez.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        icon = QtGui.QIcon.fromTheme("Excel")
        self.priloj_4_srez.setIcon(icon)
        self.priloj_4_srez.setObjectName("priloj_4_srez")
        self.otchet2859198 = QtWidgets.QPushButton(self.centralwidget)
        self.otchet2859198.setGeometry(QtCore.QRect(110, 340, 81, 31))
        self.otchet2859198.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.otchet2859198.setAccessibleDescription("")
        self.otchet2859198.setAutoFillBackground(False)
        self.otchet2859198.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        icon = QtGui.QIcon.fromTheme("Excel")
        self.otchet2859198.setIcon(icon)
        self.otchet2859198.setObjectName("otchet2859198")
        self.adi = QtWidgets.QLabel(self.centralwidget)
        self.adi.setGeometry(QtCore.QRect(420, 590, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adi.setFont(font)
        self.adi.setObjectName("adi")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 610, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 630, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.adinf = QtWidgets.QLabel(self.centralwidget)
        self.adinf.setGeometry(QtCore.QRect(520, 590, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adinf.setFont(font)
        self.adinf.setObjectName("adinf")
        self.SROKINF = QtWidgets.QLabel(self.centralwidget)
        self.SROKINF.setGeometry(QtCore.QRect(520, 610, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SROKINF.setFont(font)
        self.SROKINF.setObjectName("SROKINF")
        self.ABinf = QtWidgets.QLabel(self.centralwidget)
        self.ABinf.setGeometry(QtCore.QRect(520, 630, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ABinf.setFont(font)
        self.ABinf.setObjectName("ABinf")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 580, 81, 71))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/grog.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.froginf = QtWidgets.QLabel(self.centralwidget)
        self.froginf.setGeometry(QtCore.QRect(430, 540, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.froginf.setFont(font)
        self.froginf.setObjectName("froginf")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 530, 1201, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.checkallTime = QtWidgets.QCheckBox(self.centralwidget)
        self.checkallTime.setGeometry(QtCore.QRect(30, 550, 131, 31))
        self.checkallTime.setObjectName("checkallTime")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(860, 240, 311, 301))
        self.groupBox.setObjectName("groupBox")
        self.kkText = QtWidgets.QLabel(self.groupBox)
        self.kkText.setGeometry(QtCore.QRect(10, 20, 301, 221))
        self.kkText.setMinimumSize(QtCore.QSize(0, 0))
        self.kkText.setTextFormat(QtCore.Qt.AutoText)
        self.kkText.setScaledContents(False)
        self.kkText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.kkText.setWordWrap(True)
        self.kkText.setObjectName("kkText")
        self.smile = QtWidgets.QLabel(self.groupBox)
        self.smile.setGeometry(QtCore.QRect(210, 10, 101, 81))
        self.smile.setText("")
        self.smile.setPixmap(QtGui.QPixmap("images/smile.png"))
        self.smile.setScaledContents(True)
        self.smile.setObjectName("smile")
        self.AisInfo = QtWidgets.QLabel(self.centralwidget)
        self.AisInfo.setGeometry(QtCore.QRect(630, 260, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AisInfo.setFont(font)
        self.AisInfo.setObjectName("AisInfo")
        self.labelAisText_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelAisText_3.setGeometry(QtCore.QRect(620, 240, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.labelAisText_3.setFont(font)
        self.labelAisText_3.setObjectName("labelAisText_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(260, 0, 20, 298))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(780, 26, 71, 51))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/foxnobg.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.text107Time0 = QtWidgets.QLabel(self.centralwidget)
        self.text107Time0.setEnabled(True)
        self.text107Time0.setGeometry(QtCore.QRect(360, 50, 421, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text107Time0.sizePolicy().hasHeightForWidth())
        self.text107Time0.setSizePolicy(sizePolicy)
        self.text107Time0.setText("")
        self.text107Time0.setObjectName("text107Time0")
        self.btn_25 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_25.setGeometry(QtCore.QRect(10, 340, 91, 31))
        self.btn_25.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(112, 48,160,255) stop:0.935 rgba(223, 201, 239, 255));")
        self.btn_25.setObjectName("btn_25")
        self.renew_kkt = QtWidgets.QPushButton(self.centralwidget)
        self.renew_kkt.setGeometry(QtCore.QRect(870, 500, 91, 31))
        self.renew_kkt.setObjectName("renew_kkt")
        self.kktnalog = QtWidgets.QPushButton(self.centralwidget)
        self.kktnalog.setGeometry(QtCore.QRect(1010, 500, 91, 31))
        self.kktnalog.setObjectName("kktnalog")
        self.btn_reestr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reestr.setGeometry(QtCore.QRect(10, 10, 241, 31))
        self.btn_reestr.setWhatsThis("")
        self.btn_reestr.setAutoFillBackground(False)
        self.btn_reestr.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(0, 170, 0,255), stop:0.05 rgba(0, 170,03, 255), stop:0.935 rgba(239, 236, 55, 255));")
        self.btn_reestr.setAutoDefault(False)
        self.btn_reestr.setObjectName("btn_reestr")
        self.btn_106_fc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_106_fc.setGeometry(QtCore.QRect(700, 500, 141, 31))
        self.btn_106_fc.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(149, 228,117,255) stop:0.8 rgba(203, 147, 255, 255));")
        self.btn_106_fc.setObjectName("btn_106_fc")
        self.adinf_2 = QtWidgets.QLabel(self.centralwidget)
        self.adinf_2.setGeometry(QtCore.QRect(620, 590, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adinf_2.setFont(font)
        self.adinf_2.setObjectName("adinf_2")
        self.SROKINF_2 = QtWidgets.QLabel(self.centralwidget)
        self.SROKINF_2.setGeometry(QtCore.QRect(620, 610, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SROKINF_2.setFont(font)
        self.SROKINF_2.setObjectName("SROKINF_2")
        self.ABinf_2 = QtWidgets.QLabel(self.centralwidget)
        self.ABinf_2.setGeometry(QtCore.QRect(620, 630, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ABinf_2.setFont(font)
        self.ABinf_2.setObjectName("ABinf_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(620, 570, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(520, 570, 71, 21))
        self.label_8.setObjectName("label_8")
        self.btn_107 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_107.setGeometry(QtCore.QRect(270, 50, 81, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_107.setFont(font)
        self.btn_107.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0   rgba(112, 48,160,255) stop:0.935 rgba(223, 201, 239, 255));")
        self.btn_107.setObjectName("btn_107")
        self.prazdn = QtWidgets.QLabel(self.centralwidget)
        self.prazdn.setEnabled(True)
        self.prazdn.setGeometry(QtCore.QRect(350, 424, 311, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prazdn.sizePolicy().hasHeightForWidth())
        self.prazdn.setSizePolicy(sizePolicy)
        self.prazdn.setText("")
        self.prazdn.setPixmap(QtGui.QPixmap("images/prazdn.png"))
        self.prazdn.setScaledContents(False)
        self.prazdn.setObjectName("prazdn")
        self.btn_2013.raise_()
        self.All_bez_back.raise_()
        self.AIS_btn.raise_()
        self.progressBar.raise_()
        self.Sroki_Svod_btn.raise_()
        self.Matrica_btn.raise_()
        self.Prosrozka_btn.raise_()
        self.BLACK_Q_btn.raise_()
        self.SPY_MIN_btn.raise_()
        self.prosrozka_exc.raise_()
        self.black_q_exc.raise_()
        self.spy_min_exc.raise_()
        self.btn_106.raise_()
        self.LinkBox.raise_()
        self.label_2.raise_()
        self.calendar107.raise_()
        self.line.raise_()
        self.label_3.raise_()
        self.reservButton.raise_()
        self.FileAisInfo.raise_()
        self.labelAisText.raise_()
        self.FileAisInfo_base.raise_()
        self.labelAisText_2.raise_()
        self.reserv_adress.raise_()
        self.tableWidget101.raise_()
        self.checkBox106.raise_()
        self.info106labelTime.raise_()
        self.date106Info.raise_()
        self.vsesrazu.raise_()
        self.send_daily_stat.raise_()
        self.changedinfo.raise_()
        self.labelchanged.raise_()
        self.BIG_ZAP.raise_()
        self.toloko.raise_()
        self.blue_submit.raise_()
        self.priloj_4.raise_()
        self.BIG_SREZ.raise_()
        self.andreeva.raise_()
        self.priloj_4_srez.raise_()
        self.otchet2859198.raise_()
        self.adi.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.adinf.raise_()
        self.SROKINF.raise_()
        self.ABinf.raise_()
        self.label.raise_()
        self.froginf.raise_()
        self.line_3.raise_()
        self.checkallTime.raise_()
        self.groupBox.raise_()
        self.AisInfo.raise_()
        self.labelAisText_3.raise_()
        self.line_4.raise_()
        self.line_2.raise_()
        self.label_4.raise_()
        self.text107Time0.raise_()
        self.btn_25.raise_()
        self.renew_kkt.raise_()
        self.kktnalog.raise_()
        self.btn_reestr.raise_()
        self.btn_106_fc.raise_()
        self.adinf_2.raise_()
        self.SROKINF_2.raise_()
        self.ABinf_2.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.btn_107.raise_()
        self.prazdn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu107 = QtWidgets.QMenu(self.menu)
        self.menu107.setObjectName("menu107")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menu_3)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menu_3)
        self.menu_5.setObjectName("menu_5")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_107_recalc = QtWidgets.QAction(MainWindow)
        self.action_107_recalc.setObjectName("action_107_recalc")
        self.action_107_del = QtWidgets.QAction(MainWindow)
        self.action_107_del.setObjectName("action_107_del")
        self.option_drop = QtWidgets.QAction(MainWindow)
        self.option_drop.setObjectName("option_drop")
        self.calren = QtWidgets.QAction(MainWindow)
        self.calren.setObjectName("calren")
        self.propWindow = QtWidgets.QAction(MainWindow)
        self.propWindow.setObjectName("propWindow")
        self.action101 = QtWidgets.QAction(MainWindow)
        self.action101.setObjectName("action101")
        self.restore_csv = QtWidgets.QAction(MainWindow)
        self.restore_csv.setObjectName("restore_csv")
        self.kktperiod = QtWidgets.QAction(MainWindow)
        self.kktperiod.setObjectName("kktperiod")
        self.kktorigins = QtWidgets.QAction(MainWindow)
        self.kktorigins.setObjectName("kktorigins")
        self.menu107.addAction(self.action_107_recalc)
        self.menu107.addAction(self.action_107_del)
        self.menu.addAction(self.menu107.menuAction())
        self.menu.addAction(self.action101)
        self.menu_4.addAction(self.propWindow)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.option_drop)
        self.menu_5.addAction(self.restore_csv)
        self.menu_3.addAction(self.calren)
        self.menu_3.addSeparator()
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.menu_4.menuAction())
        self.menu_3.addAction(self.menu_5.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.kktperiod)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ПуЗо - Пульт Управления Загрузками Обновленный"))
        self.btn_2013.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.btn_2013.setStatusTip(_translate("MainWindow", "Дашборд 2013"))
        self.btn_2013.setText(_translate("MainWindow", "2013"))
        self.All_bez_back.setToolTip(_translate("MainWindow", "Запуск процедуры ALL_BEZ_BACK на 38 сервере"))
        self.All_bez_back.setStatusTip(_translate("MainWindow", "Запуск процедуры ALL_BEZ_BACK"))
        self.All_bez_back.setText(_translate("MainWindow", "ALL_BEZ_BACK"))
        self.AIS_btn.setToolTip(_translate("MainWindow", "Залить АИС"))
        self.AIS_btn.setStatusTip(_translate("MainWindow", "Залить АИС"))
        self.AIS_btn.setText(_translate("MainWindow", "АИС FKT"))
        self.Sroki_Svod_btn.setToolTip(_translate("MainWindow", "Запуск процедуры SROKI_SVOD"))
        self.Sroki_Svod_btn.setStatusTip(_translate("MainWindow", "Запуск процедуры SROKI_SVOD"))
        self.Sroki_Svod_btn.setText(_translate("MainWindow", "SROKI_SVOD"))
        self.Matrica_btn.setToolTip(_translate("MainWindow", "Запуск процедуры MATRICA"))
        self.Matrica_btn.setStatusTip(_translate("MainWindow", "Запуск процедуры MATRICA"))
        self.Matrica_btn.setText(_translate("MainWindow", "Matrica"))
        self.Prosrozka_btn.setToolTip(_translate("MainWindow", "Запуск процедуры PROSROZKA"))
        self.Prosrozka_btn.setStatusTip(_translate("MainWindow", "Запуск процедуры PROSROZKA"))
        self.Prosrozka_btn.setText(_translate("MainWindow", "Prosrozka"))
        self.BLACK_Q_btn.setToolTip(_translate("MainWindow", "Запуск процедуры BLACK_Q"))
        self.BLACK_Q_btn.setStatusTip(_translate("MainWindow", "Запуск процедуры BLACK_Q"))
        self.BLACK_Q_btn.setText(_translate("MainWindow", "BLACK_Q"))
        self.SPY_MIN_btn.setToolTip(_translate("MainWindow", "Запуск процедуры BIG_GREEN"))
        self.SPY_MIN_btn.setStatusTip(_translate("MainWindow", "Запуск процедуры BIG_GREEN"))
        self.SPY_MIN_btn.setText(_translate("MainWindow", "SPY_MINI"))
        self.prosrozka_exc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.prosrozka_exc.setStatusTip(_translate("MainWindow", "Открыть просрочку"))
        self.prosrozka_exc.setText(_translate("MainWindow", "Просрочка"))
        self.black_q_exc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.black_q_exc.setStatusTip(_translate("MainWindow", "Открыть Черный ДБ"))
        self.black_q_exc.setText(_translate("MainWindow", "Черный ДБ"))
        self.spy_min_exc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.spy_min_exc.setStatusTip(_translate("MainWindow", "Открыть Биг Грин"))
        self.spy_min_exc.setText(_translate("MainWindow", "Шпион"))
        self.btn_106.setToolTip(_translate("MainWindow", "Залить 106. С галкой справа займет много времени"))
        self.btn_106.setStatusTip(_translate("MainWindow", "Залить 106"))
        self.btn_106.setText(_translate("MainWindow", "106"))
        self.LinkBox.setItemText(0, _translate("MainWindow", "Pronto"))
        self.LinkBox.setItemText(1, _translate("MainWindow", "Глоссарий"))
        self.LinkBox.setItemText(2, _translate("MainWindow", "Заявки TFC"))
        self.LinkBox.setItemText(3, _translate("MainWindow", "Кластер"))
        self.LinkBox.setItemText(4, _translate("MainWindow", "Мониторинг"))
        self.LinkBox.setItemText(5, _translate("MainWindow", "Саппорт"))
        self.LinkBox.setItemText(6, _translate("MainWindow", "Файловое хранилище"))
        self.label_2.setText(_translate("MainWindow", "Сайты:"))
        self.calendar107.setStatusTip(_translate("MainWindow", "Невероятно, но это календарь )"))
        self.label_3.setText(_translate("MainWindow", "База 107"))
        self.reservButton.setToolTip(_translate("MainWindow", "Забрать базы данных - дело долгое и для сервера не легкое. Запускай вечером."))
        self.reservButton.setStatusTip(_translate("MainWindow", "Сделать резервную копию"))
        self.reservButton.setText(_translate("MainWindow", "Резерв 38"))
        self.FileAisInfo.setStatusTip(_translate("MainWindow", "Количество строк в файле"))
        self.labelAisText.setStatusTip(_translate("MainWindow", "Строк базе на момент последней заливки"))
        self.labelAisText.setText(_translate("MainWindow", "В базе:"))
        self.FileAisInfo_base.setStatusTip(_translate("MainWindow", "Строк базе на момент последней заливки"))
        self.labelAisText_2.setStatusTip(_translate("MainWindow", "Количество строк в файле"))
        self.labelAisText_2.setText(_translate("MainWindow", "В Файле:"))
        self.reserv_adress.setText(_translate("MainWindow", "10.252.45.177"))
        self.tableWidget101.setStatusTip(_translate("MainWindow", "Информация по 101. Сколько каждой ЖС находится в таблице"))
        self.tableWidget101.setSortingEnabled(False)
        item = self.tableWidget101.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ЖС"))
        item = self.tableWidget101.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Всего"))
        self.checkBox106.setStatusTip(_translate("MainWindow", "Выполнять-ли дистинкт таблицы после загрузки? (занимает много времени)"))
        self.checkBox106.setText(_translate("MainWindow", "Дистинкт после заливки"))
        self.info106labelTime.setStatusTip(_translate("MainWindow", "Время последней заливки 106"))
        self.info106labelTime.setText(_translate("MainWindow", "Предыдущая заливка"))
        self.date106Info.setStatusTip(_translate("MainWindow", "Время последней заливки 106"))
        self.date106Info.setText(_translate("MainWindow", "date106Info"))
        self.vsesrazu.setToolTip(_translate("MainWindow", "Запуск процедуры VSESRAZU"))
        self.vsesrazu.setStatusTip(_translate("MainWindow", "Запуск процедуры VSESRAZU"))
        self.vsesrazu.setText(_translate("MainWindow", "VseSrazu"))
        self.send_daily_stat.setText(_translate("MainWindow", "Отправить ежедн."))
        self.changedinfo.setStatusTip(_translate("MainWindow", "Что изменилось с последней резервной копии"))
        self.changedinfo.setSortingEnabled(False)
        item = self.changedinfo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Таблица"))
        item = self.changedinfo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Когда"))
        self.labelchanged.setStatusTip(_translate("MainWindow", "Время создания резервной копии"))
        self.labelchanged.setText(_translate("MainWindow", "Что поменялось"))
        self.BIG_ZAP.setToolTip(_translate("MainWindow", "Запуск процедуры BIG_ZAP"))
        self.BIG_ZAP.setStatusTip(_translate("MainWindow", "Запуск процедуры BIG_ZAP"))
        self.BIG_ZAP.setText(_translate("MainWindow", "BIG_ZAP"))
        self.toloko.setText(_translate("MainWindow", "Толоко"))
        self.blue_submit.setText(_translate("MainWindow", "17.09.2020"))
        self.priloj_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.priloj_4.setText(_translate("MainWindow", "Прилож. 4"))
        self.BIG_SREZ.setToolTip(_translate("MainWindow", "Запуск процедуры BIG_SREZ"))
        self.BIG_SREZ.setStatusTip(_translate("MainWindow", "Запуск процедуры BIG_SREZ"))
        self.BIG_SREZ.setText(_translate("MainWindow", "BIG_Срез"))
        self.andreeva.setText(_translate("MainWindow", "Андреева"))
        self.priloj_4_srez.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.priloj_4_srez.setText(_translate("MainWindow", "Прилож. 4 срез"))
        self.otchet2859198.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.otchet2859198.setText(_translate("MainWindow", "2859198_Otchet"))
        self.adi.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.adi.setText(_translate("MainWindow", "all data"))
        self.label_5.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.label_5.setText(_translate("MainWindow", "SROKI_SVOD"))
        self.label_6.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.label_6.setText(_translate("MainWindow", "ALL_BEZ_BACK"))
        self.adinf.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.adinf.setText(_translate("MainWindow", "Нет данных"))
        self.SROKINF.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.SROKINF.setText(_translate("MainWindow", "Нет данных"))
        self.ABinf.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.ABinf.setText(_translate("MainWindow", "Нет данных"))
        self.label.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.froginf.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.froginf.setText(_translate("MainWindow", "Лягушка-инфо"))
        self.checkallTime.setStatusTip(_translate("MainWindow", "Ставим галку чтобы скопировать весь сервер"))
        self.checkallTime.setText(_translate("MainWindow", "Копия всего"))
        self.groupBox.setTitle(_translate("MainWindow", "ККТ-инфо"))
        self.kkText.setStatusTip(_translate("MainWindow", "Информация по ККТ, ОКВЭД и другим базам и таблицам за последнюю неделю"))
        self.kkText.setText(_translate("MainWindow", "TextLabel"))
        self.AisInfo.setStatusTip(_translate("MainWindow", "Когда обновлялся АИС"))
        self.AisInfo.setText(_translate("MainWindow", "AISINFO"))
        self.labelAisText_3.setStatusTip(_translate("MainWindow", "Когда обновлялся АИС"))
        self.labelAisText_3.setText(_translate("MainWindow", "Когда:"))
        self.text107Time0.setStatusTip(_translate("MainWindow", "Время заливок 107 на выбранную дату"))
        self.btn_25.setToolTip(_translate("MainWindow", "Залить 25"))
        self.btn_25.setStatusTip(_translate("MainWindow", "Залить 25"))
        self.btn_25.setText(_translate("MainWindow", "25 FGT"))
        self.renew_kkt.setToolTip(_translate("MainWindow", "Обновить базу данных ЦЕН, ККТ, ОКВЭД и прочего в соответствии с выбранной датой на календаре"))
        self.renew_kkt.setText(_translate("MainWindow", "Обновить ККТ"))
        self.kktnalog.setToolTip(_translate("MainWindow", "Скачать отчеты с Кластера для kkt@nalog.ru. Уйдет на рабочий стол"))
        self.kktnalog.setText(_translate("MainWindow", "Cluster.ZIP"))
        self.btn_reestr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Если не срабатывает, то<span style=\" font-weight:600;\"> &quot;Опции&quot; - &quot;Настройки&quot; - &quot;Настройки&quot;,</span> где надо указать верный путь до Excel 2013</p></body></html>"))
        self.btn_reestr.setStatusTip(_translate("MainWindow", "Дашборд 2013"))
        self.btn_reestr.setText(_translate("MainWindow", "Реестр заявок"))
        self.btn_106_fc.setToolTip(_translate("MainWindow", "Залить 106. С галкой справа займет много времени"))
        self.btn_106_fc.setStatusTip(_translate("MainWindow", "Залить 106"))
        self.btn_106_fc.setText(_translate("MainWindow", "106 FOREIGN KEY TEST"))
        self.adinf_2.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.adinf_2.setText(_translate("MainWindow", "Нет данных"))
        self.SROKINF_2.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.SROKINF_2.setText(_translate("MainWindow", "Нет данных"))
        self.ABinf_2.setStatusTip(_translate("MainWindow", "Сводные данные таблиц, по которым прыгает ЛЯГУШКА"))
        self.ABinf_2.setText(_translate("MainWindow", "Нет данных"))
        self.label_7.setText(_translate("MainWindow", "Приход:"))
        self.label_8.setText(_translate("MainWindow", "В базе"))
        self.btn_107.setToolTip(_translate("MainWindow", "Залить 107. Необходим файл выгрузки "))
        self.btn_107.setStatusTip(_translate("MainWindow", "Залить 107"))
        self.btn_107.setText(_translate("MainWindow", "107 FKT"))
        self.menu.setTitle(_translate("MainWindow", "Пульт"))
        self.menu107.setStatusTip(_translate("MainWindow", "Работа со 107"))
        self.menu107.setTitle(_translate("MainWindow", "107"))
        self.menu_3.setTitle(_translate("MainWindow", "Опции"))
        self.menu_4.setTitle(_translate("MainWindow", "Настройки"))
        self.menu_5.setTitle(_translate("MainWindow", "Резерв"))
        self.menu_2.setTitle(_translate("MainWindow", "ККТ"))
        self.action_107_recalc.setText(_translate("MainWindow", "Пересчитать 107"))
        self.action_107_recalc.setStatusTip(_translate("MainWindow", "Обновить данные по 107"))
        self.action_107_del.setText(_translate("MainWindow", "Удалить заливку"))
        self.action_107_del.setStatusTip(_translate("MainWindow", "Удалить случайно загруженный 107"))
        self.option_drop.setText(_translate("MainWindow", "Сброс настроек"))
        self.option_drop.setStatusTip(_translate("MainWindow", "Сбросить настройки"))
        self.calren.setText(_translate("MainWindow", "Обновить инфо"))
        self.propWindow.setText(_translate("MainWindow", "Настройки"))
        self.propWindow.setStatusTip(_translate("MainWindow", "Открыть настройки для приложения"))
        self.action101.setText(_translate("MainWindow", "FroG-Info"))
        self.action101.setStatusTip(_translate("MainWindow", "Запуск Лягушки"))
        self.restore_csv.setText(_translate("MainWindow", "Восстановить из csv"))
        self.restore_csv.setStatusTip(_translate("MainWindow", "Восстановить из ранее подготовленных csv на чистую таблицу"))
        self.kktperiod.setText(_translate("MainWindow", "Операции"))
        self.kktorigins.setText(_translate("MainWindow", "Оригиналы.Zip"))
